name: build and test

on:
  push:
    branches: main
    paths-ignore:
      - '*.md'

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        llvm:
          - 21
        platform:
          - ubuntu-24.04
          - macos-26
        build:
          - { optimize: O1, sanitize: none,      loglevel: trace }
          - { optimize: O2, sanitize: address,   loglevel: error }
          - { optimize: O2, sanitize: undefined, loglevel: error }
          - { optimize: O2, sanitize: none,      loglevel: error }
          - { optimize: O3, sanitize: none,      loglevel: error }
        include:
          - llvm: 21
            platform: ubuntu-24.04
            build: { optimize: O2, sanitize: memory, loglevel: error }

    name: "${{ matrix.platform }} optimize=${{ matrix.build.optimize }} sanitize=${{ matrix.build.sanitize }}"
    runs-on: ${{ matrix.platform }}
    env:
      OPTIMIZE: ${{ matrix.build.optimize }}
      SANITIZE: ${{ matrix.build.sanitize }}
      SL_LOGGING_LEVEL: ${{ matrix.build.loglevel }}

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: install linux dependencies
      if: startsWith(matrix.platform, 'ubuntu')
      run: |
        sudo apt update --yes && sudo apt install --yes libopenblas-dev jq
        wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | sudo tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc
        sudo add-apt-repository --yes "deb http://apt.llvm.org/noble/ llvm-toolchain-noble-${{ matrix.llvm }} main"
        sudo apt update --yes && sudo apt install --yes clang-${{ matrix.llvm }} lld-${{ matrix.llvm }} clang-format-${{ matrix.llvm }} clang-tidy-${{ matrix.llvm }}

    - name: install macOS dependencies
      if: startsWith(matrix.platform, 'macos')
      run: brew install coreutils llvm@${{ matrix.llvm }} lld@${{ matrix.llvm }}

    - name: verify Makefile parses
      run: make help

    - name: build
      run: make -j4 all

    - name: compile_commands.json
      run: make compile_commands.json

    - name: test
      run: make test

    - name: integration test
      run: make integration_test
